version: "3.7"

networks:
  default:
    driver: bridge

services:
  database:
    image: postgres:12
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
